### ISSUE TITLE
Cypher/GFQL: multi-alias WITH prefix projection for bounded reentry

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#1047]
## Summary

`MATCH (a)-[r]->(b) WITH a, b OPTIONAL MATCH (b)-[r2:T]->(c) RETURN a.id, b.id, c.id` fails:

```
[unsupported-cypher-query] Cypher row lowering currently supports one MATCH source alias at a time
```

The bounded reentry prefix compiles `WITH a, b` as `RETURN a, b` (whole-row), which is a multi-alias whole-row projection from a connected pattern — not supported.

## Context

- Parent: #996 (OPTIONAL MATCH umbrella)
- Blocked by: multi-alias whole-row `RETURN` from connected MATCH patterns
- The single-alias case (`WITH x OPTIONAL MATCH ...`) is fixed by #1026 / #1044
- TCK scenario: `match-where6-5` (partially — it also needs cross-alias WHERE)

## Pre-existing

This compilation error exists on current master. Not a regression from #1026.
